<Countdown>
    text: str(round(self.countdown, 1))

<StrikeCounter>
    canvas:
        Rectangle:
            pos: self.center_x - 5, 0
            size: 10, self.height



    Label:
        font_size: 70
        center_x: root.width / 4
        top: root.top - 50
        text: str(root.strike_count)

    Label:
        font_size: 70
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: root.time_elapsed


    #count:
